# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import rapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_auto_20170501_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='issued',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True, validators=[rapp.models.validate_token]),
        ),
    ]
